const mongoose = require('mongoose')
const packageSchema =new mongoose.Schema ({
    at1:{
        type:String,
        required:true
    },
    ac1:{
        type:String,
        required:true
    },
    af1:{
        type:String,
        required:true
    },
    a1:{
        type:String,
        required:true
    },
    ac2:{
        type:String,
        required:true
    },
    a2:{
        type:String,
        required:true
    },
    ac3:{
        type:String,
        required:true
    },
    af2:{
        type:String,
        required:true
    },
    a3:{
        type:String,
        required:true
    },
    c1:{
        type:String,
        required:true
    },
    t1:{
         type:String,
        required:true
    },
    b1:{
        type:String,
        required:true
    },
    bt1:{
        type:String,
        required:true
    },
    bc1:{
        type:String,
        required:true
    },
    bf1:{
        type:String,
        required:true
    },
    b1:{
        type:String,
        required:true
    },
    bc2:{
        type:String,
        required:true
    },
    b2:{
        type:String,
        required:true
    },
    bc3:{
        type:String,
        required:true
    },
    bf2:{
        type:String,
        required:true
    },
    b3:{
        type:String,
        required:true
    },
    c2:{
        type:String,
        required:true
    },
    t2:{
        type:String,
        required:true
    }
    


})
const packages =new mongoose.model('packages',packageSchema)
module.exports = packages